from math import pi

D_BIN_SIZE = 50
D_MIN_TOLERABLE = 0
D_MAX_TOLERABLE = 2500

VEL_BIN_SIZE = 3/60 
VEL_MIN_TOLERABLE = -4 # m/s
VEL_MAX_TOLERABLE = 4 # m/s

VELDIFF_BIN_SIZE = 0.5 / 60 
VELDIFF_MIN_TOLERABLE = 0 # m/s
VELDIFF_MAX_TOLERABLE = 0.5 # m/s

VDDOT_BIN_SIZE = 2 * pi / 60 
VDDOT_MIN_TOLERABLE = -pi # radians
VDDOT_MAX_TOLERABLE = pi# radians

VVDOT_BIN_SIZE = 2 * pi / 60 
VVDOT_MIN_TOLERABLE = -pi # radians
VVDOT_MAX_TOLERABLE = pi # radians

HEIGHT_BIN_SIZE = 7.5 # cm 
HEIGHT_MIN_TOLERABLE = 1000 # mm
HEIGHT_MAX_TOLERABLE = 2100 # mm

HEIGHTDIFF_BIN_SIZE = 7.5 # cm
HEIGHTDIFF_MIN_TOLERABLE = 0 # mm
HEIGHTDIFF_MAX_TOLERABLE = 2100 # m

VELOCITY_THRESHOLD = 0.5 # m/s
DISTANCE_THRESHOLD = 2000 # mm

HISTOG_PARAM_TABLE = {
    'd': (D_MIN_TOLERABLE, D_MAX_TOLERABLE, D_BIN_SIZE),
    'v_g': (VEL_MIN_TOLERABLE, VEL_MAX_TOLERABLE, VEL_BIN_SIZE),
    'v_diff': (VELDIFF_MIN_TOLERABLE, VELDIFF_MAX_TOLERABLE, VELDIFF_BIN_SIZE),
    'vv_dot': (VVDOT_MIN_TOLERABLE, VVDOT_MAX_TOLERABLE, VVDOT_BIN_SIZE),
    'vd_dot': (VDDOT_MIN_TOLERABLE, VDDOT_MAX_TOLERABLE, VDDOT_BIN_SIZE),
    'h_avg': (HEIGHT_MIN_TOLERABLE, HEIGHT_MAX_TOLERABLE, HEIGHT_BIN_SIZE),
    'h_diff': (HEIGHTDIFF_MIN_TOLERABLE, HEIGHTDIFF_MAX_TOLERABLE, HEIGHTDIFF_BIN_SIZE),
    'h_short': (HEIGHT_MIN_TOLERABLE, HEIGHT_MAX_TOLERABLE, HEIGHT_BIN_SIZE),
    'h_tall': (HEIGHT_MIN_TOLERABLE, HEIGHT_MAX_TOLERABLE, HEIGHT_BIN_SIZE)
}
