from math import pi

"""
Modeling parameters/variables for delta and vel
"""
   
D_BIN_SIZE = 50
D_MIN_TOLERABLE = 0
D_MAX_TOLERABLE = 2500

VEL_BIN_SIZE = 3/60 
VEL_MIN_TOLERABLE = -3 # m/s
VEL_MAX_TOLERABLE = 3 # m/s

VELDIFF_BIN_SIZE = 0.5 / 60 
VELDIFF_MIN_TOLERABLE = 0 # m/s
VELDIFF_MAX_TOLERABLE = 0.5 # m/s

VDDOT_BIN_SIZE = 2 * pi / 60 
VDDOT_MIN_TOLERABLE = -pi # radians
VDDOT_MAX_TOLERABLE = pi# radians

VVDOT_BIN_SIZE = 2 * pi / 60 
VVDOT_MIN_TOLERABLE = -pi # radians
VVDOT_MAX_TOLERABLE = pi # radians

HEIGHT_BIN_SIZE = 7.5 # cm 
HEIGHT_MIN_TOLERABLE = 1000 # mm
HEIGHT_MAX_TOLERABLE = 2100 # mm

HEIGHTDIFF_BIN_SIZE = 7.5 # cm
HEIGHTDIFF_MIN_TOLERABLE = 0 # mm
HEIGHTDIFF_MAX_TOLERABLE = 2100 # m

VELOCITY_THRESHOLD = 0.5 # m/s
DISTANCE_THRESHOLD = 2000 # mm